### ISSUE TITLE
tell singleton

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#10]
The ev-trace and ev-reach functions only differ in that they use tell-trace and tell-reach giving either singleton sets or lists respectively.  Is there some way to unify this and get use a ev-tell function that just uses the underlying tell operation?  In order to this, tell needs to take an element rather than a collection.

Just a thought as I write about this stuff.  Trace and reach have a lot in common but their difference just comes down to 1) names and 2) constructing different singletons.

**Comment by davdar** [comment]
Yeah you could do this in an analogous way to the way we treat the store. Give an abstract interface to `tell`, call it `output`, where `output` takes a single element, and the implementation of `output` decides whether or not the element should be smashed into a set or concatenated to a list. Then both `ev-reach` and `ev-trace` can be the same evaluator parameterized over this `output` interface.

**Comment by davdar** [comment]
In fact, I think it makes a nice story this way; since the store is an abstract interface, and it can choose how it stores things (single-vs-set), also make the output an abstract interface, and it can choose how it outputs things (list-vs-set).

**Comment by dvanhorn** [comment]
I guess what I want is for output to use the List0 or Pow0 to know how to add things.

**Comment by davdar** [comment]
Ah right, the monad needs ListO or PowO to know how to combine things... I guess if you go this route, you're looking at two different monad stacks, one for `ev-reach` and one for `ev-trace`, and two different implementations of `output`, one which knows the output is a list and concats to the end, and one which knows the output is a set and adds it to the set. Hm.

**Comment by davdar** [comment]
whereas currently, you only need one monad stack for both evaluators I think.

**Comment by davdar** [comment]
oh shit no, you need two different monads. ListO vs PowO, event for the current setup.

**Comment by dvanhorn** [comment]
That's right: currently there are two stacks.  I think what would be better is two stacks, but one ev-tell "mixin".  But I'm currently just sweeping this under the rug.

**Comment by labichn** [comment]
Potential solution in #11. This is the best we can do with the current signatures. DD, is there a name for monoids with a singleton injection (e.g. `(λ (x) (set x))`, `(λ (x) (list x))`)? We could unify the evs if we gave that a name (or just hid it behind your proposed `output`).
