### ISSUE TITLE
monad for nd and finite store

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#13]
Can someone implement a monad with non-determinism and a set-based store (that joins)?  Basically it should be like monad-pdcfa minus all the cache stuff.

**Comment by philnguyen** [comment]
Is this already achievable by existing units? (Using `monad-nd.rkt` and `state-nd.rkt`)

Example:

``` racket
#lang monadic-eval (monad-nd@ alloc-0cfa@ state-nd@ δ@ ev!@) (fix ev!)

((λ (f) (+ (f 1) (f 2))) (λ (x) x))

;; ==>
;; (set '(2 . (("x" . #<set: 1 2>) ("f" . #<set: ((lam x (vbl x)) . ())>)))
;;      '(3 . (("x" . #<set: 1 2>) ("f" . #<set: ((lam x (vbl x)) . ())>))))
```

**Comment by dvanhorn** [comment]
Thanks!

**Comment by labichn** [comment]
Pushed in bff24202b096db0517ba421998e1b029db598425.
