### ISSUE TITLE
StateT #f

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#15]
What's the role of #f in the StateT monad stacks?

**Comment by labichn** [comment]
It is a placeholder for an optional underlying monoid (should be prettier--but I don't know whether there's better ways to do optional arguments on the left of required arguments other than macros). You can see monad/monad-pdcfa.rkt for an example of StateT using #f (for the value store, composed outside of the NondetT so it inherits the set monoid's `mzero` and `mplus` operations) and another StateT using `(FinMapO PowerO)`, which holds the local cache for a coinductive run.

If there's an underlying monoid (like with Nondet or Fail) you can inherit their structure. When there isn't (in the case of the local cache), you have to specify how two of the values held by the StateT are joined. (FinMapO PowerO) is a finite map with sets as the cod, there're other examples in transformers.rkt.

**Comment by davdar** [comment]
For the paper, you could rename `StateT #f` to just `StateT` and call `StateT SomeMonoid` something like `MergeStateT SomeMonoid` or `JoinStateT SomeMonoid`. Would be an easy change to the code too.

**Comment by davdar** [comment]
It's definitely weird even for people familiar with monad transformers to see StateT taking a monoid arguments. That's a Galois Transformers specific thing.

**Comment by dvanhorn** [comment]
OK; mostly I'm concerned about the paper, so I will follow this suggestion (and not mess with the code).
