### ISSUE TITLE
What's the difference between cycle detection and single cache?

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#16]
I was trying to tell a story that goes:
1. cycle detection
2. simple caching (i.e. single cache)
3. meta caching and outer fixedpoint.

There is code for all three, see monad-cache.rkt and ev-cache0.rkt for 2.

But I think I've gotten myself lost.  Can anyone come up with an example where 1 and 2 produce different results?

**Comment by philnguyen** [comment]
I guess `2` depends on branch traversal order and in worst the case, it reaches all the recursive calls first and can't use cache from base cases, therefore equivalent (in terms of result) to `1`?

``` racket
(letrec ([sum
          (λ (n)
            (if (= n 0)
                0
                (+ n (sum (- n 1)))))])
  (let ([double-sum
         (λ (n)
           (+ (sum n) (sum n)))])
    (double-sum 'N)))

;; Cycle:
;; (+ {0} {0}) --> 0

;; Cache: best case, reaching base cases first:
;; 2nd call to `sum n` reads `{0, N}` from cache
;; (+ {0, N} {0, N}) --> {0, N}
```

**Comment by dvanhorn** [comment]
I ended up just skipping over the cyclic case.  Maybe with more time we could come up with a better story, but I think what's there is OK for now.
