### ISSUE TITLE
Cite two diss on PDCFA?

### ISSUE THREAD

**Issue by davdar** [plum-umd/monadic-eval#33]
https://github.com/plum-umd/monadic-eval/blob/a72f1a0fe380bcc51b6ed9dc872e1732875dffae/monadic-eval/paper2/05-reynolds.tex#L27-L28

Maybe this should be "two dissertations", and we should mention Chris Earls' diss?

**Comment by dvanhorn** [comment]
Yes, can you do it?

**Comment by davdar** [comment]
Yep; on it.

**Comment by davdar** [comment]
Done.
