### ISSUE TITLE
Back to Scribble

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#34]
I'm sorry to say this document needs to go back to Scribble.  The formalism section can remain as tex, but the rest needs to be ported back.  It's important to having running examples and I'm not going to bake them in by hand.

**Comment by davdar** [comment]
I remember trying this but couldn't figure out how to do it. Scribble requires a header of latex imports which are incompatible with basic math typesetting packages like amsmath. If someone can figure out how to support the basic imports needed for the formalism section (like amsmath) within a scribble doc, I'm happy to help port it back.

**Comment by dvanhorn** [comment]
You can just leave that section in tex and import it from the scribble file.  I will set up a small template.

**Comment by davdar** [comment]
Sounds good. Thanks.

**Comment by dvanhorn** [comment]
It's going to be more involved than I thought because of the new "acmart" class.
