### ISSUE TITLE
for/monad simplification

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#41]
> Page 10:
> (for/monad+ ([v (σ a)]) (return v))
> is this not the same as (σ a)?

Double check and simplify if so.

**Comment by davdar** [comment]
It's not the same, but we should still explain slash clarify.

**Comment by dvanhorn** [comment]
@davdar can you add a clarification?

**Comment by davdar** [comment]
Yeah, this is the pattern: `(for/monad+ ([v X]) (return v))`. In this pattern, `X` has type `m(set(A))` and the result of the expression has type `m(A)`. The pattern takes the set of values returned by the "computation" `X`, and internalizes each of those results into the nondeterminism effect of the monad.

Here's a simple concrete example of what it's doing:
``````````````````````````
(for/monad+ ([v (return {1,2,3})] (return v)))
=
(mplus (return 1) (return 2) (return 3))
`````````````````````````````

@labichn, can you confirm this is indeed what's happening here? I think `for/monad+` was your creation, and I'm only 90% sure about the above explanation.

**Comment by davdar** [comment]
Er, the `{1,2,3}` above should be `(set 1 2 3)`. Sorry for the quasi-Racket-maths syntax.

**Comment by dvanhorn** [comment]
We're overdue on the camera-ready version. Can you guys make progress on this and suggest an edit for the paper (or argue that one isn't needed)?

**Comment by labichn** [comment]
Sorry for the delay--the comprehension is correct. Our map's application just returns the value and the `for/monad+` handles the `mplus`. DD's explanation is spot-on.

**Comment by davdar** [comment]
I don't think it's an essential point that needs addressing. There is already text in the paper which explains for/monad+. In 03-interp.scrbl:

> The @racket[for/monad+] form is a convenience for combining a set of
> computations with @racket[mplus], and is used so @racket[find] returns
> @emph{all} of the values in the store at a given address.

I say just leave it.
