### ISSUE TITLE
put-cache iteration

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#43]
> In the definition of $+ in Figure 9, why is (put-cache-out ∅) run on each iteration?

Well...

**Comment by dvanhorn** [comment]
@davdar @labichn Can you guys look at this and see if there needs to be a better explanation?

**Comment by davdar** [comment]
I can take a look.

**Comment by davdar** [comment]
What I came up with: a1cb1b4716c5ebcd8

**Comment by labichn** [comment]
I took a pass over your changes, let me know what you think: 573354c1d058c2c2d44f716b316af2a43b6832c8

**Comment by davdar** [comment]
A nice improvement. Looks good to me. Thanks @labichn.

**Comment by dvanhorn** [comment]
LGTM.  Thanks!
