### ISSUE TITLE
Clarify: some infeasible paths

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#44]
> Page 17:
> "allowing the elimination of infeasible paths": of "some infeasible paths", right?

Sure.

**Comment by philnguyen** [comment]
Are these different?...

**Comment by dvanhorn** [comment]
I believe the reader read the original as "allowing the elimination of (all) infeasible paths" instead of "some".

**Comment by dvanhorn** [comment]
I resolved with "provably" to hint that it's not all infeasible paths, just those that you can prove can't happen (which will be incomplete).  I thought the original was fine, too, for the record.
