### ISSUE TITLE
Rename concrete units

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#5]
I'd like to rename the concrete units to drop the `-con` and `-base` suffixes.  The baseline should look like something you'd write if you never had an abstract interpreter in mind.

So con-ex0.rkt (I don't care about file names, that's fine) should look like

```
#lang monadic-eval (ev@ monad@ alloc@ delta@) (fix ev)
```

Also, can we rename `delta@` to `δ@`?

**Comment by davdar** [comment]
Yeah I agree on all points.

**Comment by labichn** [comment]
This just involves changing the #lang racket/unit to #lang racket and naming things by hand, rather than getting the names from the source files. I'll take care of it.

**Comment by davdar** [comment]
Why not just rename the source files?

**Comment by dvanhorn** [comment]
Unicode file names are probably not a good idea.

**Comment by davdar** [comment]
Right. Only do that for the Unicode ones then. Rename the others.

**Comment by labichn** [comment]
Done in f56a27454c506413a8e6684ac65faf1f5d20fa0f.
