### ISSUE TITLE
Clarify (or remove) restriction on rec

### ISSUE THREAD

**Issue by dvanhorn** [plum-umd/monadic-eval#51]
> Fig 2. The implementation of rec seems to assume that the first expression is definitely going to be a lambda. It would be nice if either Fig. 1 made that clear or if it weren't required (e.g. I might try to implement mutual recursion by producing a pair of functions and projecting on recursions). I recommend the former.

I think we should clarify rather than relax the restriction.  We could play around with the second solution though; if it's clean, that's fine.

**Comment by dvanhorn** [comment]
If someone wants to play with removing the restriction, be my guest, but I don't see how to do it simply and it needs to be simple at this point in the paper.

**Comment by davdar** [comment]
I think we should either (A) make it syntactically a lambda (rather than syntactically any value), or (B) just relax the requirement and allow any expression there. (B) is actually pretty easy I think; might be worth doing (here's the code):

`````````````````````````````````
[(rec x e₀ e₁)  (do ρ  ← ask-env  a  ← (alloc x)
                    ρ′ ≔ (ρ f a)
                    v ← (local-env ρ′ (ev e₀))
                    (ext a v)
                    (local-env ρ′ (ev e₁)))]
``````````````````````````````````````

**Comment by dvanhorn** [comment]
Ah, right, I forgot things are easy with store allocated bindings -- you just extend the environment but not the heap, which will explode if you touch the recursively bound variable too soon.  I like this and will change it.  (BTW, I did fix it originally by saying it syntactically had to be a lambda, but I said value in the prose.)

**Comment by dvanhorn** [comment]
BTW, this skates close to something pretty subtle once things are abstracted.  For a buggy program that touches the rec variable too soon, you want to be sure that's (abstractly) interpreted as an error and not an empty set in the store.  Otherwise things are unsound.  I believe that's what our interpreter will do since there's a difference between an address pointing to the empty set and an address not being there.  But we should confirm.

**Comment by davdar** [comment]
Hm, good point. Can we put a simple test case into the test suite for this?

**Comment by dvanhorn** [comment]
Yes, I'll do that before closing.

**Comment by dvanhorn** [comment]
There is a wrinkle with this approach: it breaks GC because it creates dangling pointers.  When GC goes to crawl the heap, it crashes chasing the reference.  It's probably easy to hack the GC to handle this case, but then it won't crash whenever there is a truly invalid pointer in the heap.

**Comment by davdar** [comment]
maybe we need an explicit "undefined" value? this would handle your comment above about interpreting touching a rec variable too soon as an error, as well as cooperate better with GC.

**Comment by davdar** [comment]
Admittedly this would muddy up the clean presentation and design we have in the paper now with a new class of values that is only used in this subtle way... I'm currently 50/50 split on just patching the GC or doing something like my suggestion...

**Comment by dvanhorn** [comment]
OK, I implemented this and fixed up GC.  It still causes problems for the reference counting GC, but @labichn will have to fix that.

**Comment by dvanhorn** [comment]
And I have some test cases I will check in later.

**Comment by dvanhorn** [comment]
I went ahead and removed the restriction in the paper, but I haven't closed this issue because I think it may be better to have a non-let-like form that just does recursive binding, i.e. `(rec f e)` which is equivalent to `(rec f e f)` in the current formulation.  This makes the evaluator slightly simpler and the examples become `((rec f (λ (x) ...) e)` instead of `(rec f (λ (x) ...) (f e))`.

**Comment by davdar** [comment]
Yeah I like that simplification.

**Comment by dvanhorn** [comment]
Simplified now.
