### ISSUE TITLE
parameterize store update strategy in delta interface

### ISSUE THREAD

**Issue by davdar** [plum-umd/monadic-eval#6]
we need a (merge old new) function, defined in the delta interface. the concrete version returns `new`, the abstract version will perform `(set-union old new)`.

**Comment by labichn** [comment]
Mostly done in ea66c441d5d0d53fece46dd0f9e69248a49032f7.
Abstract versions currently only defined for non-ref ev (will be extended).
Does the symbolic version ever get more than one value in the store? Phil should write the join for that one, if so.

**Comment by labichn** [comment]
I no longer think this is the correct solution. We need to solve another issue at the same time: variable lookup is currently not monadic.

This is a fairly important design question. DD removed the `state^` unit which handled variable lookup, variable binding, and recursive variable binding. The base evaluator's variable lookup now assumes the codomain of the store is only ever `value`. There are two solutions that I see.
1. Write an `ev-*` interpreter extension that overrides `vbl`, `lrc`, and `app` functionality to expect sets in the store's codomain.
2. Recreate the state^ (or better named) signature in a limited way: `find : string -> addr -> M value`, `ext : string -> addr -> value -> M unit`.

I believe (2) is the better solution. Not only would the majority of the code in the interpreter extension be duplicated, but we would a need a different `ev-*` extension to get the alternate crushing join into the store that duplicates it all again.

Originally, the functions `find`, `ext`, and `rext` had the types `string -> M value`, `string -> value -> M unit`, and `string -> exp -> M value`, respectively. This let us abstract over different state-space component structures (using Racket's heap, boxes, or explicit), but hid too much from the interpreter's implementation (including calls to `alloc`). With allocation and closure creation being handled in the interpreter, much less is hidden than the original interface and the single `ext` can handle the recursive and non-recursive joins into the store. This also removes the need for this addition to the `delta^` signature.

I'm going to implement (2), but I wanted to make sure the decision is open for discussion. Let me know if (1) or a solution I don't see is preferable.

**Comment by davdar** [comment]
let's come to consensus before you make such an invasive change to the design.

How does vbl need to change between concrete and abstract values (which are powersets)? isn't vbl always just "look up address for variable in environment, look up value for address in store"?

**Comment by labichn** [comment]
No need to rewrite `delta^`s for powersets if we let NondetT handle the store's nondeterminism. Isn't this (monadic variable lookup) how every monadic AAM has been presented?

**Comment by davdar** [comment]
no, in AAM variable lookup should return a set of values, not branch nondeterministically on each element of the powerset.

when you need to eliminate a value (if statements and apply), that's when you move the powerset from the value into the nondeterminism of the monad. that's what truish? is doing, and you need an analogous operator for lambda as part of the delta interface (lambdish? : val -> M(clo)) vs (truish? : val -> M(bool)), where val is concrete in the concrete case, and a powerset in the abstract case.

**Comment by labichn** [comment]
Nope, in AAM, variable lookup immediately branches (page 5, figure 5: http://matt.might.net/papers/vanhorn2010abstract.pdf).

To be clear, you're proposing a new `delta^` for sets of abstract values, two additions to `delta^`'s signature (`\sqcup` to join values on store extension and `lambdaish?` to branch on apply), and an interpreter extension that returns singleton sets at the leaves (`num`, `lam`)?

I disagree that this is preferable to two one-liner metafunctions `find` and `ext`, especially since we're diverging from AAM's original presentation. Does anyone else have an opinion?

**Comment by davdar** [comment]
Okay, DVH and I just chatted and Nick your design is the intended one.

Delta should never be operating over sets of things, and variable lookup shouldn't return sets of things, even in the case where "heap values" are power sets of individual "abstract values".

The solution we want is a hybrid of where we started and where we are now: before we abstracted both the environment and store away, so there was an abstract interface dealing just with values, and there was an explicit recursive variant for putting recursive bindings in the "store". currently the environment and store are both fully transparent, and this would require delta operating over power sets and such.

Nick: go ahead an re-introduce the store^ interface. It should only need get/put/update, and it should take addresses explicitly.

**Comment by labichn** [comment]
Cool--glad I mentioned it before just running with it. Thanks for the discussion.

**Comment by davdar** [comment]
Nick, does this mean we don't need join as part of the delta interface anymore?

**Comment by dvanhorn** [comment]
Seems weird to me to have join in delta.

**Comment by labichn** [comment]
If we remove, then each `state^` implementation will be tied to a particular abstract value space. It doesn't seem that odd to me to have a join operation in our `delta^`, since each `delta^` also implicitly defines the lattice of values, but I'm happy either way.

**Comment by davdar** [comment]
I guess there's two types of implementations for state^: one which maps directly to abstract values, and one which maps to sets of abstract values. Assuming the first implementation (mapping directly) is only for concrete stuff, we don't need join there, and if all of the abstract interpreters use the mapping to sets, then join is always set union. If we want to support stores that map to single values (not sets) and also do sound approximation (joins) then we'll need join in something like delta^. Not sure if we have an example that looks like this for the paper though, so I say just drop join.

**Comment by labichn** [comment]
`state^` changes are stable in a085ad69e3bf650b84c82d107d490c874376fb10. I couldn't bear to write a `find : var -> addr -> M value` where the first argument is universally ignored, so I wrote `find : var -> M value` instead.
