### ISSUE TITLE
Complete and test memo-fixpoint evaluator/ev-combinator

### ISSUE THREAD

**Issue by davdar** [plum-umd/monadic-eval#7]
See fix-party.rkt from commit 2a8e50d544c9d83cf231b5566d0e285205d3a337 for a reference implementation that's 98% there. Relevant functions are `caching`, `memoify` and `mlfp`. Definitely rename `memoify`; I rather like the names `caching` and `mlfp`. ("mlfp" stands for "monadic least fixed point".)

**Comment by labichn** [comment]
Baseline implementation was pushed in eaaac4e5349f70524c228ac58ceb5232c12cc394.

I was unsuccessful at composing NondetT and FailT in the way we agreed upon (returning `(failure)`) instances as values, but I realized this is probably not what we want. We're in a world with re-functionalized control-flow, so we shouldn't have defunctionalized exceptions floating around. The proper way to implement exceptions is to stop transitioning (until we hit the top-level or a try effect), not return an exception as a value.

If I recall correctly, the concern is that `fail` in a NondetT context without the literal `(failure)` is observationally equivalent to not exploring that path at all. I suspect we'd get all that information back if we added in an `ev-{trace,reachable}`. I'll do some testing with this later today.

**Comment by dvanhorn** [comment]
I guess I'm confused: I never thought failures were _values_, they are answers.  (In whiteboard discussions we've been saying the result of evaluation is M(value) but it's really M(answer).)  If we're talking about pdfca, you should get a set of values and failures.  I don't understand what "defunctionalized exceptions" mean.  This is just the usual failure monad; you don't (return (fail)), you (fail).  bind should check if you got a failure before continuing.  Make sense?  If you look at the old code all this was spelled out.

**Comment by labichn** [comment]
Failure is working as expected, and four PDCFA variants were pushed in 4093f65f3dd7b6c848c4205cb953b32de6ea88fa:
- pdcfa + delta-abs (bounces any primop to top)
- pdcfa + delta-pres (preserves precision in primops, crushing values on join into the heap)
- widened pdcfa + delta-abs
- widened pdcfa + delta-pres
